LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := YYDRobotLockScreen
LOCAL_MODULE_TAGS := optional	

ifeq ($(WAKE_UP_NAME),)
LOCAL_SRC_FILES := xiaoyong.apk
else
LOCAL_SRC_FILES := $(WAKE_UP_NAME).apk
endif


LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

LOCAL_MULTILIB :=32
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)
